### ISSUE TITLE
Mobile display suggestion 

### ISSUE THREAD

**Issue by WayoutYT** [ScratchTutorials/ScratchTutorials#27]
I think we should use that kind of navbar:

```html
<nav class="navbar">
  <!---->
</nav>
<nav class="navbar-mobile">
  <!---->
</nav>
```

```css
@media only screen and (max-width: 360px) {
  .navbar-mobile {
     display: block;
  } 
  .navbar {
     display: none;
  } 
} 
```
